services:
  ebook-api:
    image: ghcr.io/camilalemes/ebook-management-api:latest
    container_name: ebook-management-api
    restart: unless-stopped
    environment:
      # Calibre Library Configuration (Windows PC via SMB)
      - CALIBRE_LIBRARY_PATH=/pc-shares/calibre-library
      - REPLICA_PATHS=/pc-shares/ebook-replicas,/data/ebook-replicas
      - CALIBRE_CMD_PATH=calibredb
      # API Configuration
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - API_VERSION=1.0.0
      - API_DEBUG=false
      # Logging
      - LOG_LEVEL=INFO
      - LOG_FILE=/config/logs/app.log
      # User/Group IDs (match homelab setup)
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TZ}
      
    volumes:
      # Config and logs (following your pattern)
      - ${CONFIG_PATH}/ebook-management-api:/config
      # NAS ebook replicas (direct mount like other services)
      - ${MEDIA_PATH}/ebook-replicas:/data/ebook-replicas
      # PC SMB shares (OneDrive Calibre + fallback replica)
      - type: volume
        source: pc-calibre-library
        target: /pc-shares/calibre-library
        read_only: true
      - type: volume
        source: pc-ebook-replicas
        target: /pc-shares/ebook-replicas
    networks:
      - home

    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Wait for PC SMB mounts
    depends_on:
      pc-smb-mounts:
        condition: service_healthy
    labels:
      # Traefik integration
      - traefik.enable=true
      - traefik.http.routers.ebook-api.rule=Host("ebook.lemoes-nest.home")
      - traefik.http.services.ebook-api.loadbalancer.server.port=8000

      # Watchtower integration
      - com.centurylinklabs.watchtower.enable=true

  # PC SMB mounts service (only for Windows PC shares)
  pc-smb-mounts:
    image: alpine:latest
    container_name: ebook-pc-smb-mounts
    restart: unless-stopped
    privileged: true
    command: >
      sh -c "
      echo 'Installing SMB utilities...' &&
      apk add --no-cache cifs-utils curl &&
      
      echo 'Creating mount points...' &&
      mkdir -p /mnt/calibre-library /mnt/ebook-replicas &&
      
      echo 'Waiting for PC...' &&
      until ping -c 1 ${PC_IP} &> /dev/null; do 
        echo 'PC not reachable, waiting...'
        sleep 10
      done &&
      
      echo 'Mounting SMB shares from Windows PC...' &&
      mount -t cifs //${PC_IP}/CalibreLibrary /mnt/calibre-library -o ro,username=${PC_SMB_USER},password=${PC_SMB_PASS},uid=${USER_ID},gid=${GROUP_ID} &&
      mount -t cifs //${PC_IP}/EbookReplicas /mnt/ebook-replicas -o rw,username=${PC_SMB_USER},password=${PC_SMB_PASS},uid=${USER_ID},gid=${GROUP_ID} &&
      
      echo 'PC SMB mounts ready!' &&
      tail -f /dev/null
      "
    environment:
      # PC configuration
      - PC_IP=${PC_IP:-192.168.50.245}
      - PC_SMB_USER=${PC_SMB_USER:-guest}
      - PC_SMB_PASS=${PC_SMB_PASS:-}
      - USER_ID=${USER_ID}
      - GROUP_ID=${GROUP_ID}
    volumes:
      # Share PC mounts with main app container
      - pc-calibre-library:/mnt/calibre-library:shared
      - pc-ebook-replicas:/mnt/ebook-replicas:shared
    networks:
      - home
      
    healthcheck:
      test: >
        sh -c "
        mountpoint -q /mnt/calibre-library &&
        mountpoint -q /mnt/ebook-replicas
        "
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

# Only PC SMB volumes needed (NAS uses direct host mount)
volumes:
  pc-calibre-library:
    driver: local
  pc-ebook-replicas:
    driver: local