services:
  ebook-api:
    image: ghcr.io/camilalemes/ebook-management-api:latest
    container_name: ebook-management-api
    restart: unless-stopped
    environment:
      # Library Configuration (NAS only - read-only)
      - LIBRARY_PATHS=/data/ebook-library
      - CALIBRE_CMD_PATH=calibredb
      # Logging
      - LOG_LEVEL=INFO
      - LOG_FILE=/config/logs/app.log
      # User/Group IDs
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TZ}

    volumes:
      # Config and logs
      - ${CONFIG_PATH}/ebook-management-api:/config
      # NAS ebook library (read-only access)
      - ${MEDIA_PATH}/ebook-library:/data/ebook-library:ro
    networks:
      - home

    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    # No dependencies - reads directly from NAS
    labels:
      # Traefik integration
      - traefik.enable=true
      - traefik.http.routers.ebook-api.rule=Host("ebook.lemoes-nest.home")
      - traefik.http.services.ebook-api.loadbalancer.server.port=8000

      # Watchtower integration
      - com.centurylinklabs.watchtower.enable=true

networks:
  home:
    external: true